version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: mypostgres
      POSTGRES_PASSWORD: opklnm123
      POSTGRES_DB: dating
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bubble

  dating-service:
    container_name: dating-service
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: cmd/DockerfileDev
    ports:
      - '5004:5004'
    networks:
      - bubble
    depends_on:
      - postgres


volumes:
  postgres-data:

networks:
  bubble:
